# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 481d7b91e3801a50490b89ba03fb26dda6b1ceec3bda6904c6b512026c80517b4c33871e98aa89462a28deec6e3ab62efd354f64d36546aa2a572f787638c0c7

test:
  secret_key_base: 9c4685761cb0105774bb7a3c47d493830f1116b22165e19ab95190b61dcd7c3f32853db53524ae845db5f30829d2fc9315c9aedff0fa7c3b7c92d20fa326c300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
